module javafx {
    requires javafx.graphics;
    requires javafx.controls;
    requires javafx.fxml;
    requires lombok;
    requires org.apache.logging.log4j;
    requires jakarta.inject;
    requires jakarta.cdi;
    requires io.vavr;
    exports ui.screens.orders.deleteorders;
    exports services.impl;
    exports dao.imp;
    exports model;
    exports ui.main to javafx.graphics;
    exports ui.screens.principal;
    exports ui.screens.login;
    exports ui.screens.common;
    exports ui.screens.customers.addcustomer;
    exports ui.screens.customers.showcustomers;
    exports ui.screens.customers.deletecustomer;
    exports ui.screens.customers.editcustomers;
    exports ui.screens.orders.listorders;
    exports ui.screens.orders.addorder;

    exports common;
    opens ui.screens.common;
    opens ui.screens.login;
    opens ui.screens.customers.editcustomers;
    opens ui.screens.principal;
    opens ui.main;
    opens ui.screens.orders.listorders;
    opens css;
    opens fxml;
    opens ui.screens.orders.addorder;
    opens ui.screens.orders.editorder;
    opens ui.screens.customers.addcustomer;
    opens ui.screens.customers.deletecustomer;
    opens ui.screens.customers.showcustomers;
    opens ui.screens.orders.deleteorders;
    exports dao;
    exports dao.imp.staticlists;
    exports dao.imp.files;
}
